### PR TITLE
Enforce single quotes for jsx attributes.

### PR DESCRIPTION
**Pull request by KevinGrandon**

### CODE REVIEW

**Comment by zackargyle** [comment]
:+1:

**Comment by chrislloyd** [comment]
Eww.

**Comment by KevinGrandon** [comment]
We use single quotes everywhere in javascript. It seems weird to me to switch to double quotes inside of JSX. Better to keep things consistent IMO.

**Comment by bradencanderson** [comment]
Coming back to this -- we should do it for consistency.

**Pull request merged**
